### ISSUE TITLE
 init.cpp:548] Cannot activate tls logger plugin: No node key, TLS logging disabled.

### ISSUE THREAD

**Issue by foreversunyao** [mwielgoszewski/doorman#88]
Hi ,
  When I run (ENROLL_SECRET=secret osqueryd --flagfile osquery.flags) , I found this errors:

W1007 18:42:01.073891 28081 tls.cpp:75] Failed enrollment request to https://10.65.16.129:5000/opt/enroll (Request error: certificate verify failed) retrying...
I1007 18:42:01.078042 28081 tls.cpp:216] TLS/HTTPS POST request to URI: https://10.65.16.129:5000/opt/enroll
{"enroll_secret":"secret","host_identifier":"4eaf24e7-8385-4e56-93cd-5f7d052289f0"}

E1007 18:42:01.080790 28081 init.cpp:548] Cannot activate tls logger plugin: No node key, TLS logging disabled.

**Comment by foreversunyao** [comment]
Hi all,
    Because after I finished my configuration, I request the url https://localhost:5000/manage/
And return this error info:


webassets.exceptions.FilterError
FilterError: Program file not found: lessc.

Traceback (most recent call last)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
return view_func(**req.view_args)
File "/usr/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
return func(*args, **kwargs)
File "/data/doorman-master/doorman/manage/views.py", line 57, in index
return render_template('index.html')
File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
context, ctx.app)
File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
rv = template.render(context)
File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
return self.environment.handle_exception(exc_info, True)
File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
reraise(exc_type, exc_value, tb)
File "/data/doorman-master/doorman/templates/manage/index.html", line 1, in top-level template code
{% extends "layout.html" %}
File "/data/doorman-master/doorman/templates/layout.html", line 23, in top-level template code
{% assets "css_all" %}
File "/usr/local/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 186, in _render_assets
urls = bundle.urls()
File "/usr/local/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
File "/usr/local/lib/python2.7/site-packages/webassets/bundle.py", line 758, in _urls
*args, **kwargs))
File "/usr/local/lib/python2.7/site-packages/webassets/bundle.py", line 746, in _urls
*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/webassets/bundle.py", line 600, in _build
force, disable_cache=disable_cache, extra_filters=extra_filters)
File "/usr/local/lib/python2.7/site-packages/webassets/bundle.py", line 524, in _merge_and_apply
kwargs=item_data)
File "/usr/local/lib/python2.7/site-packages/webassets/merge.py", line 276, in apply
return self._wrap_cache(key, func)
File "/usr/local/lib/python2.7/site-packages/webassets/merge.py", line 218, in _wrap_cache
content = func().getvalue()
File "/usr/local/lib/python2.7/site-packages/webassets/merge.py", line 251, in func
getattr(filter, type)(data, out, **kwargs_final)
File "/usr/local/lib/python2.7/site-packages/webassets/filter/less.py", line 139, in input
self._apply_less(_in, out, source_path)
File "/usr/local/lib/python2.7/site-packages/webassets/filter/less.py", line 131, in _apply_less
self.subprocess(args, out, in_)
File "/usr/local/lib/python2.7/site-packages/webassets/filter/__init__.py", line 516, in subprocess
raise FilterError('Program file not found: %s.' % argv[0])
FilterError: Program file not found: lessc.

**Comment by foreversunyao** [comment]
And I fixed the problem above, but a new error happened.


File "/usr/local/lib/python2.7/site-packages/webassets/filter/__init__.py", line 523, in subprocess
proc.returncode, stdout, stderr))
FilterError: less: subprocess returned a non-success result code: 1, stdout=, stderr=[31mFileError: '../libs/bootstrap/less/bootstrap.less' wasn't found. Tried - ../libs/bootstrap/less/bootstrap.less,../libs/bootstrap/less/bootstrap.less[39m[31m in [39m-[90m on line 1, column 1:[39m 1 [7m[31m[1m@[22mimport "../libs/bootstrap/less/bootstrap.less";[39m[27m [90m2 @import "font-awesome.less";[39m[0m[0m

**Comment by mwielgoszewski** [comment]
Hi @foreversunyao - what steps did you take to create the certificate? osquery is failing to establish a connection because the certificate is not valid (likely due to a mismatch in the subject field of the certifcate and the hostname you're using for doorman).

**Comment by foreversunyao** [comment]
Hi mwielgoszewski,

    I only typed the command from the guide "**openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout private.key -out certificate.crt**" and no input any param, so is it all use default values ?

**Comment by foreversunyao** [comment]
And Can I use no certificate and use http only for doorman manage osquey?

**Comment by mwielgoszewski** [comment]
@foreversunyao you need to generate a certificate that's valid for the hostname - i.e., certificate with subject / common name of `10.65.16.129`.

**Comment by foreversunyao** [comment]
@mwielgoszewski 
   Can we define the path of certificate.crt and private.key ? or their name and path are hard-coded ? I don't find related configures in setting.py.

**Comment by foreversunyao** [comment]
@mwielgoszewski 
I found these two files configuration in manage.py, and fix the problem before, but after I run 
ENROLL_SECRET=secret osqueryd --flagfile osquery.flags.

there error like this:
W1012 17:32:14.870569 140672 tls.cpp:75] Failed enrollment request to https://10.65.16.129:5000/opt/enroll (JSON deserialize error: <unspecified file>(2): expected value) retrying.

**Comment by mwielgoszewski** [comment]
@foreversunyao There are several incorrect flags in your `osquery.flags` file. Notably:

* `config_tls_endpoint` should be `/config`
* `enroll_tls_endpoint` should be `/enroll`
* `distributed_tls_read_endpoint` should be `/distributed/read`
* `distributed_tls_write_endpoint` should be `/distributed/write`
* `logger_tls_endpoint` should be `/log`
* `pack_delimiter` should be `/`

With regards to the TLS key and certificate - manage.py is used for development purposes, and those values are and will remain hardcoded. Python, and Flask web applications (and Doorman is no exception) are typically deployed using [uWSGI](http://flask.pocoo.org/docs/0.11/deploying/uwsgi/) or [gunicorn](http://flask.pocoo.org/docs/0.11/deploying/wsgi-standalone/#gunicorn), and have [nginx](http://flask.pocoo.org/docs/0.11/deploying/wsgi-standalone/#proxy-setups) or apache configured to proxy requests to their workers.

**Comment by foreversunyao** [comment]
@mwielgoszewski Thanks for your help. It works.
Yes, we just only test this website function because it is python and flask, and will deploy it at nginx later if it meet our requirements.
Anyway, thanks you again.
