### ISSUE TITLE
docker image doesn't work (timeout)

### ISSUE THREAD

**Issue by knqyf263** [mwielgoszewski/doorman#95]
I ran the `doorman` image by docker.
```
root@vagrant-ubuntu-trusty-64:/home/vagrant/doorman# docker run -e DOORMAN_ENROLL_SECRET=secret -e DOORMAN_SECRET_KEY=secret -e POSTGRES
_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_PORT=5432 -p 5000:5000 doorman
[2016-12-06 13:07:53 +0000] [8] [INFO] Starting gunicorn 19.6.0
[2016-12-06 13:07:53 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
[2016-12-06 13:07:53 +0000] [8] [INFO] Using worker: sync
[2016-12-06 13:07:53 +0000] [23] [INFO] Booting worker with pid: 23
[2016-12-06 13:07:53 +0000] [24] [INFO] Booting worker with pid: 24
[2016-12-06 13:07:53 +0000] [25] [INFO] Booting worker with pid: 25
[2016-12-06 13:07:53 +0000] [26] [INFO] Booting worker with pid: 26

 -------------- celery@9a0bdf8d08f9 v3.1.23 (Cipater)
---- **** -----
--- * ***  * -- Linux-3.13.0-101-generic-x86_64-with
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         doorman.tasks:0x7fdbf4ff7550
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[tasks]
  . doorman.tasks.analyze_result
  . doorman.tasks.example_task
  . doorman.tasks.learn_from_result
[2016-12-06 13:07:55,879: INFO/MainProcess] Connected to redis://localhost:6379/0
[2016-12-06 13:07:55,888: INFO/MainProcess] mingle: searching for neighbors
[2016-12-06 13:07:56,895: INFO/MainProcess] mingle: all alone
[2016-12-06 13:07:56,903: WARNING/MainProcess] celery@9a0bdf8d08f9 ready.
[2016-12-06 13:08:42 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:25)
[2016-12-06 13:08:42 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:23)
[2016-12-06 13:08:42 +0000] [25] [INFO] Worker exiting (pid: 25)
[2016-12-06 13:08:42 +0000] [23] [INFO] Worker exiting (pid: 23)
[2016-12-06 13:08:42 +0000] [52] [INFO] Booting worker with pid: 52
[2016-12-06 13:08:42 +0000] [53] [INFO] Booting worker with pid: 53
[2016-12-06 13:16:23 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:53)
[2016-12-06 13:16:23 +0000] [53] [INFO] Worker exiting (pid: 53)
[2016-12-06 13:16:23 +0000] [97] [INFO] Booting worker with pid: 97
```

Then, I tried accessing to `http://127.0.0.1:5000`,but no response(timeout?)

```
vagrant@vagrant-ubuntu-trusty-64:~/doorman$ curl https://127.0.0.1:5000
curl: (35) Unknown SSL protocol error in connection to 127.0.0.1:5000
vagrant@vagrant-ubuntu-trusty-64:~/doorman$ wget https://127.0.0.1:5000
--2016-12-07 05:51:08--  https://127.0.0.1:5000/
Connecting to 127.0.0.1:5000... connected.
Unable to establish SSL connection.
```

I checked syslog. These were empty.
```
vagrant@vagrant-ubuntu-trusty-64:~/doorman$ sudo docker exec -it 435c2309050b ls -al /var/log/doorman
total 8
drwxr-xr-x    2 doorman  doorman       4096 Dec  7 04:31 .
drwxr-xr-x    6 root     root          4096 Dec  7 04:31 ..
-rw-r--r--    1 doorman  doorman          0 Dec  7 04:31 doorman.log
-rw-r--r--    1 doorman  doorman          0 Dec  7 04:31 result.log
-rw-r--r--    1 doorman  doorman          0 Dec  7 04:31 status.log
```

Our environment is the following:
```
vagrant@vagrant-ubuntu-trusty-64:~/doorman$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

vagrant@vagrant-ubuntu-trusty-64:~/doorman$ docker --version
Docker version 1.12.3, build 6b644ec
```

In what environment does docker image work correctly?

**Comment by mwielgoszewski** [comment]
Hi @knqyf263, can you try curling http://localhost:5000/manage ? The root index should return an HTTP 204 No Content (which won't show anything in the browser).

**Comment by knqyf263** [comment]
@mwielgoszewski Thanks for your reply!

I tried curling http://127.0.0.1:5000/manage, but the result was the same.
Does it work in your environment?
```
vagrant@vagrant-ubuntu-trusty-64:~/doorman$ curl http://127.0.0.1:5000/manage
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="https://127.0.0.1:5000/manage">https://127.0.0.1:5000/manage</a>.  If not click the link.
vagrant@vagrant-ubuntu-trusty-64:~/doorman$ curl https://127.0.0.1:5000/manage
curl: (35) Unknown SSL protocol error in connection to 127.0.0.1:5000
```

**Comment by mwielgoszewski** [comment]
@knqyf263 sorry for the late reply. I the problem you're running into is that the Doorman application is running on the localhost without SSL, though it assumes a web server like nginx or apache or acting as a reverse proxy, with SSL enabled on them. Thus why you're seeing a request to http:// redirect to https://.

I recommend running nginx as a reverse proxy, bound to an external interface and proxying requests to Doorman running in a wsgi container, which is exposed on a local domain socket or port on localhost.

See the following Flask documentation for more info:
- http://flask.pocoo.org/docs/0.11/deploying/wsgi-standalone/
- http://flask.pocoo.org/docs/0.11/deploying/uwsgi/

I think our current Docker image could use some work here. Unfortunately, neither @andrew-d or I use it regularly, so we haven't given it as much attention.

 In the short term, you can probably set `ENFORCE_SSL` to `False` and `PREFERRED_URL_SCHEME` to `http`, as a workaround, but you'll want to get SSL working for osqueryd to work with it.

**Comment by knqyf263** [comment]
@mwielgoszewski Thanks for your reply! I understood.
I tried running nginx as a reverse proxy and got the following error:

```
2016-12-16 10:38:30,881 -  doorman.application - ERROR - 139779642456872 - Exception on /manage/packs [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/src/doorman/manage/views.py", line 253, in packs
    packs = Pack.query.options(joinedload(Pack.queries).joinedload(Query.packs)).all()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2588, in all
    return list(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) relation "pack" does not exist
LINE 2: FROM pack LEFT OUTER JOIN (query_packs AS query_packs_1 JOIN...
             ^
 [SQL: 'SELECT pack.id AS pack_id, pack.name AS pack_name, pack.platform AS pack_platform, pack.version AS pack_version, pack.description AS pack_description, pack.shard AS pack_shard, pack_1.id AS pack_1_id, pack_1.name AS pack_1_name, pack_1.platform AS pack_1_platform,
 pack_1.version AS pack_1_version, pack_1.description AS pack_1_description, pack_1.shard AS pack_1_shard, tag_1.id AS tag_1_id, tag_1.value AS tag_1_value, query_1.id AS query_1_id, query_1.name AS query_1_name, query_1.sql AS query_1_sql, query_1.interval AS query_1_int
erval, query_1.platform AS query_1_platform, query_1.version AS query_1_version, query_1.description AS query_1_description, query_1.value AS query_1_value, query_1.removed AS query_1_removed \nFROM pack LEFT OUTER JOIN (query_packs AS query_packs_1 JOIN query AS query_1
ON query_1.id = query_packs_1."query.id") ON pack.id = query_packs_1."pack.id" LEFT OUTER JOIN (query_packs AS query_packs_2 JOIN pack AS pack_1 ON pack_1.id = query_packs_2."pack.id") ON query_1.id = query_packs_2."query.id" LEFT OUTER JOIN (query_tags AS query_tags_1 JO
IN tag AS tag_1 ON tag_1.id = query_tags_1."tag.id") ON query_1.id = query_tags_1."query.id"']
```

I think that `postgres` is not initialized.
`doorman` image is executed by the following command.

```
$ docker run --name doorman -d -e DOORMAN_ENROLL_SECRET=foo -e DOORMAN_SECRET_KEY=secret-key -e POSTGRES_USER=doorman -e POSTGRES_PASSWORD=pass -p 5000:5000 --link postgres doorman
```

Then, I initialized postgres manually.

```
$ docker exec -it doorman bash
bash-4.3# cd /src
bash-4.3# echo $POSTGRES_PORT
tcp://172.17.0.37:5432
bash-4.3# export DOORMAN_ENV=prod
bash-4.3# export DOORMAN_SETTINGS=$PWD/settings.cfg
bash-4.3# python manage.py db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> d2b00dd93241, Initial revision for migrations going forward.
INFO  [alembic.runtime.migration] Running upgrade d2b00dd93241 -> fd28e46e46a6, Add rule table to configure rules and alerts.
INFO  [alembic.runtime.migration] Running upgrade fd28e46e46a6 -> 0bc0a93ac867, Add user table to support doorman and oauth authentication.
INFO  [alembic.runtime.migration] Running upgrade 0bc0a93ac867 -> 14c992522209, Add version field introduced in osquery v1.7.4.
INFO  [alembic.runtime.migration] Running upgrade 14c992522209 -> 4f95ecd76bf8, Normalize distributed query architecture
INFO  [alembic.runtime.migration] Running upgrade 4f95ecd76bf8 -> b50c705fea80, Migrate to new rules architecture
INFO  [alembic.runtime.migration] Running upgrade b50c705fea80 -> c17f01adbe31, Add "updated_at" column to Rule
INFO  [alembic.runtime.migration] Running upgrade c17f01adbe31 -> 54ef3f06612c, Add "node_info" column to capture arbitrary node information on the fly
INFO  [alembic.runtime.migration] Running upgrade 54ef3f06612c -> 236318ee3d3e, Add is_active and last_ip columns to node table
```

Finally, I accessed normally.

I want `doorman` to initialize automatically.
How should it be fixed?
I think that `manage.py db upgrade` should be executed when `docker run`.

**Comment by knqyf263** [comment]
Additionally, I got the following error:
```
2016-12-16 11:12:13,274 -  doorman.application - ERROR - 140104870370088 - Exception on /manage/rules [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/src/doorman/manage/views.py", line 625, in rules
    return render_template('rules.html', rules=rules)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/src/doorman/manage/../templates/manage/rules.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/src/doorman/templates/layout.html", line 23, in top-level template code
    {% assets "css_all" %}
  File "/usr/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/usr/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/usr/lib/python2.7/site-packages/webassets/bundle.py", line 746, in _urls
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/webassets/bundle.py", line 590, in _build
    if ctx.updater else True
  File "/usr/lib/python2.7/site-packages/webassets/updater.py", line 173, in needs_rebuild
    super(TimestampUpdater, self).needs_rebuild(bundle, ctx) or \
  File "/usr/lib/python2.7/site-packages/webassets/updater.py", line 103, in needs_rebuild
    return self.check_bundle_definition(bundle, ctx)
  File "/usr/lib/python2.7/site-packages/webassets/updater.py", line 93, in check_bundle_definition
    cached_hash = ctx.cache.get(cache_key)
  File "/usr/lib/python2.7/site-packages/webassets/cache.py", line 184, in get
    f = open(filename, 'rb')
IOError: [Errno 13] Permission denied: '/src/doorman/static/.webassets-cache/37e68119d46ebec91663d2a5b4b16945'
```

`doorman` user doesn't have the write permission to `/src/doorman/static/.webassets-cache/`
I ran `$ chown -R doorman:doorman /src`.
The error has been resolved.

**Comment by mwielgoszewski** [comment]
@knqyf263 Do you think you can summarize all the commands you had to run to get the Docker image working or submit a PR? Would love to get your feedback merged into master based on your experience.
