### ISSUE TITLE
Can't get doorman to initialize the postgres database

### ISSUE THREAD

**Issue by alsmola** [mwielgoszewski/doorman#97]
I can't get doorman to initialize the postgres database using the provided scripts.

I'm trying to run doorman and postgres as docker containers (linked) on my Mac. I'm using the (official)[https://hub.docker.com/_/postgres/] postgres docker image.

I've created the DB in postgres, and I'm trying to initialize it from the doorman docker container by running `python manage.py db upgrade`:

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
```

The database isn't on localhost. I notice on the doorman container the `POSTGRES_PORT` environment variable is set to (correctly, I believe) to `tcp://172.17.0.2:5432`

Peeking around a bit in the source, I noticed that there's (`is_offline_mode`)[https://github.com/mwielgoszewski/doorman/blob/master/migrations/env.py#L84] condition. I was able to hit that path with the `python manage.py db upgrade --sql` flag, but then I see a bunch of SQL statements followed by this error:

```
SELECT id, status, retrieved, guid, node_id
        FROM distributed_query
        ORDER BY id;;

Traceback (most recent call last):
  File "manage.py", line 101, in <module>
    manager.run()
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_migrate/__init__.py", line 235, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 86, in <module>
    run_migrations_offline()
  File "migrations/env.py", line 47, in run_migrations_offline
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/src/migrations/versions/4f95ecd76bf8_normalize_distributed_query_architecture.py", line 43, in upgrade
    results = map(DistributedQueryTask._make, cursor.fetchall())
AttributeError: 'NoneType' object has no attribute 'fetchall'
```

I also had to create a reverse proxy and change the source permissions, per https://github.com/mwielgoszewski/doorman/issues/95

**Comment by alsmola** [comment]
I was able to resolve this by manually setting the `SQLALCHEMY_DATABASE_URI` in the `doorman/settings.py` file. It seems like the `migrations/env.py` file isn't reading the `settings.cfg` file.
